/**
 * CeraCUT Build Info
 * Zeigt Versionsinformationen in der Console
 */

const CERACUT_BUILD = {
    version: '6.0',
    build: '20260315-leadprofiles',
    date: '2026-03-15',
    time: '23:59 MEZ',

    modules: {
        'dxf-parser':         { version: '3.8', build: '20260312-textglyphs' },
        'geometry':           { version: '2.9', build: '20260128-0645' },
        'pipeline':           { version: '3.2', build: '20260315-bugfix35' },
        'cam-contour':        { version: '5.1', build: '20260315-clearance' },
        'canvas-renderer':    { version: '3.17', build: '20260315-discfill' },
        'undo-manager':       { version: '1.1', build: '20260309-wizard' },
        'sinumerik-pp':       { version: '1.5', build: '20260315-safety' },
        'command-line':       { version: '1.2', build: '20260315-ux' },
        'snap-manager':       { version: '1.3', build: '20260315-bugfix35' },
        'geometry-ops':       { version: '2.4', build: '20260315-bugfix35' },
        'drawing-tools':      { version: '2.5', build: '20260315-bugfix35' },
        'drawing-tools-ext':  { version: '1.1', build: '20260311-overlapbreak' },
        'dynamic-input':      { version: '1.0', build: '20260309-dynhud' },
        'tool-manager':       { version: '2.2', build: '20260216-0015' },
        'layer-manager':      { version: '1.0', build: '20260215-2200' },
        'text-tool':          { version: '1.2', build: '20260312-textimport' },
        'dxf-writer':         { version: '1.2', build: '20260315-bugfix35' },
        'lead-profiles':      { version: '1.0', build: '20260315-leadprofiles' },
        'app':                { version: '6.0', build: '20260315-leadprofiles' },
        'project-manager':    { version: '1.0', build: '20260313-workspace' },
        'properties-panel':   { version: '1.2', build: '20260315-ctxmenu' },
        'debug-monitor':      { version: '1.0', build: '20260219-dm10' },
        'nesting':            { version: '1.1', build: '20260315-bugfix35' },
        'toolpath-simulator': { version: '1.0', build: '20260309' },
        'cost-calculator':    { version: '1.1', build: '20260315-bugfix35' },
        'machine-profiles':   { version: '1.0', build: '20260309' },
        'bridge-cutting':     { version: '1.0', build: '20260309' },
        'quality-zones':      { version: '1.1', build: '20260315-bugfix35' },
        'advanced-tools':     { version: '1.4', build: '20260315-bugfix35' },
        'arc-fitting':        { version: '3.1', build: '20260315-bugfix35' }
    },
    
    changes: [
        'V3.5: Tier 2 Modification Tools — Move (M), Copy (Shift+C), Rotate (R), Mirror (Shift+M), Scale (S), Erase (DEL)',
        'V3.5: Always-Active ToolManager — Zeichnen + Modifikation ohne F2-Toggle',
        'V3.5: Noun-Verb + Verb-Noun Selektion (AutoCAD-Stil)',
        'V3.5: Window-Selection (Drag-Rechteck): Links→Rechts = Window, Rechts→Links = Crossing',
        'V3.5: Ghost-Preview (halbtransparent) für Move/Copy/Rotate/Mirror/Scale',
        'V3.5: Selektion in allen Steps (nicht nur 4/5) für Noun-Verb Workflow',
        'V3.5: Klick auf leere Fläche → Selektion aufheben',
        'V3.5: Escape-Kaskade: Tool → Messmodus → Startpunkt → Selektion',
        'V3.5: DEL-Taste startet EraseTool (mit Undo) statt hartem Löschen',
        'V3.5: Offset-Tool vorbereitet (Platzhalter für V2.1)',
        'V3.5-fix: Auto-Apply gezeichnete Entities bei Mod-Tool-Start',
        'V3.5-fix: CamContour Klassenname korrigiert (war CAMContour)',
        'V3.5-fix: LineTool S/C = Linienzug schließen (AutoCAD-Stil)',
        'V3.5-fix: Rechtsklick = Bestätigen bei aktivem Tool (AutoCAD-Stil)',
        'V3.5-fix: fileLoaded bei Drawing-Only (Step-Navigation ohne DXF)',
        'V3.7: Tier 4 Aufteilen — CL2D (Halbieren), CLND (N-Teilen), CLDCL (Divided Calculation Dialog)',
        'V3.7: Ribbon-Gruppe "Aufteilen" im Start-Tab mit 3 Werkzeugen',
        'V3.7: CLDCL 5 Modi: Fest-einseitig, Fest-beidseitig, Fest-Mitte, Gleich-Anzahl, Gleich-MaxLänge',
        'V3.7: Joint/Fugen-Berechnung bei Aufteilung',
        'V3.7: Senkrechte Teilungslinien als echte LINE-Entities (direkt nutzbar)',
        'V3.8: Layer-System — AutoCAD-Style Ribbon + Status-Bar Dropdowns',
        'V3.8: Layer-Manager Dialog (Layer CRUD, Farbe, Sichtbarkeit, Lock, Linientyp)',
        'V3.8: DXF-Writer R12 (AC1009) — Speichern + Speichern unter (Strg+S/Strg+Shift+S)',
        'V3.8: Layer-Import aus DXF, Entity-Counts, ACI-Farbkonvertierung',
        'V3.6: Tier 3 Phase A — GeometryOps Engine V1.0 (Intersection, Segment-Modell)',
        'V3.6: Explode (X) — Konturen in Einzelsegmente zerlegen',
        'V3.6: Join (J) — Konturen zu Polylinie verbinden',
        'V3.6: Break (B) — Kontur an Punkt teilen (offen/geschlossen)',
        'V3.6: LineTool S/C = Linienzug schließen',
        'V3.6: Rechtsklick = Bestätigen bei aktivem Tool (AutoCAD-Stil)',
        'V3.6: Toolbar-Buttons für Tier 3 Tools',
        'V3.4: CAD Drawing Tools — Line (L), Circle (C), Rectangle (N), Arc (A), Polyline (P)',
        'V3.4: AutoCAD-style Command-Line UI mit Koordinateneingabe (absolut + relativ)',
        'V3.4: SnapManager V1.0 — Endpoint, Midpoint, Center, Intersection, Nearest',
        'V3.4: Ortho-Modus (F8) für 0°/90° Constraint',
        'Sinumerik 840D Postprozessor V1.0: Echte CNC-Ausgabe im MPF-Format',
        'UndoManager V1.0: Command Pattern (Undo/Redo), Clipboard (Copy/Cut/Paste)',
        'DXF-Parser V3.0: SPLINE Flags Fix (Bit 8=planar, nicht periodic)',
        'DXF-Parser V3.3: CRITICAL FIX — LWPOLYLINE 1000-Zeilen-Limit entfernt (abgeschnittene Konturen)',
        'DXF-Parser V3.3: Layer-aware Chaining — Segmente verschiedener Layer nicht mehr gemischt',
        'DXF-Parser V3.3: Erweiterte Diagnostik (Entity-Typ-Breakdown, Kontur-Details, Vertex-Validierung)',
        'V3.8-fix: tool-manager.js Section 4 Duplikate entfernt (LineTool already declared)',
        'V5.2: Intarsien-Modus — Dual-Export NEG/POS mit invertierter Kerf-Kompensation',
        'V5.2: CuttingMode-Alternation nach Nesting-Level (A/O/B Sonderfälle)',
        'V5.2: CAM-Tab Intarsien-Gruppe (Toggle, Fugenbreite, NEG/POS-Preview)',
        'V5.2: clone() überträgt nestingLevel für Intarsien-Kontur-Klone',
        'V5.3 Phase B: Piercing Types (6 IGEMS: auto/blind/linear/stationary/circular/drilling/air_start)',
        'V5.3 Phase B: R923 dynamisch im Postprozessor (nicht mehr hardcoded 9)',
        'V5.3 Phase B: R924 (Standzeit), R925 (Kreisradius), R926 (Kreiszeit) bei speziellen Typen',
        'V5.3 Phase B: Dynamic Lead (B.2) — Binary-Search Kollisionsvermeidung',
        'V5.3 Phase B: Flächenklassen (B.3) — 6 IGEMS-Standard-Klassen für Löcher',
        'V5.3 Phase B: Properties Panel — Piercing/Lead-In/Area-Class Controls',
        'V5.3 Phase B: clone() für alle B.1/B.2 Properties erweitert',
        'V5.3 Phase B: properties-panel-styles.css verlinkt (war bisher missing)',
        'Debug Monitor V1.0: Globaler Error-Catcher (onerror+unhandledrejection+console.error)',
        'Debug Monitor V1.0: 13 bekannte CeraCUT-Fallen automatisch erkannt und erklärt',
        'Debug Monitor V1.0: Session-Log (200 Fehler), Action-Tracker (50 Aktionen)',
        'Debug Monitor V1.0: Performance-Monitor Frame-Drop-Erkennung (>50ms)',
        'Debug Monitor V1.0: Overlay Strg+Shift+D — 4 Tabs (Fehler/Aktionen/Perf/Fallen)',
        'Debug Monitor V1.0: JSON-Export für Claude Code Analyse',
        'V5.4 Phase B UI: Piercing-Typ Dropdown (5 Typen) + R924/R925/R926 konditionale Felder',
        'V5.4 Phase B UI: Dynamic Lead Checkbox + Min/Max-Eingabefelder',
        'V5.4 Phase B UI: Flächenklassen-Checkbox + Editor-Popup (6 IGEMS-Klassen, editierbar)',
        'V5.4 Phase B UI: Single-Mode Button (manuelle Fahnenplatzierung per Klick + Undo)',
        'V5.4 Phase B UI: Lead-Favoriten (Speichern/Laden/Löschen, localStorage-Persistenz)',
        'V5.4 Phase B UI: Alle B.1-B.6 UI-Handler im Shim verdrahtet + Live-Preview',
        'V5.4.1 Fix: Gelbe Messlinien bleiben nach Messmodus-Ende nicht mehr stehen',
        'V5.4.1 Fix: ACI 7 Layer-Farben invertieren bei Theme-Wechsel (weiß↔schwarz)',
        'V5.4.1: Kontur-Kontextmenü — Nullpunkt → Endpunkt / Nullpunkt → Mittelpunkt',
        'V5.4.1: Echte ctx.arc() Darstellung für Arc-Leads (statt 12-Segment Polyline)',
        'V5.4.1: Arc-Metadaten (arcStartAngle, arcEndAngle, arcSweepCCW) in cam-contour',
        'V5.4.2: Arabeske-Tool (AB) — Parametrische Laternenfliese (8 Kreisbögen) in advanced-tools.js V1.2',
        'V5.4.2: GeometryOps V2.2 — _circumscribedCircle, _arcThrough3Points, createArabeske',
        'V5.4.2: Fugen-Offset für tessellierbare Fliesenverlegung (2mm Standard)',
        'V5.4.2: Ribbon-Button "Arabeske" im CAD-Tab Zeichnen-Gruppe',
        'V5.5.0: Multi-Kontur Collision Detection — Lead vs. ALLE Konturen (cam-contour V4.7)',
        'V5.5.0: DXF TEXT/MTEXT/HATCH Support (dxf-parser V3.5)',
        'V5.5.0: Nesting Engine V1.0 — BLF-Algorithmus, Multi-Rotation, Multi-Sheet',
        'V5.5.0: Toolpath Simulator V1.0 — Pfad-Verifikation, Animation, Kollisionsmatrix',
        'V5.5.0: Cost Calculator V1.0 — Kosten-/Zeitkalkulation mit CeraJet-Integration',
        'V5.5.0: Machine Profiles V1.0 — Maschinenpark-Verwaltung, PP-Profile, localStorage',
        'V5.5.0: Bridge Cutting V1.0 — Haltestege zwischen Teilen (auto/manuell)',
        'V5.5.0: Quality Zones V1.0 — Auto-Erkennung von Ecken/Radien für Speed-Reduktion',
        'V5.5.0: Sinumerik PP V1.3 — Multi-Head Support, Machine-Profile Integration',
        'V5.5.0: WizardStepUndo V1.1 — Verschachteltes Undo pro Wizard-Step',
        'V5.5.0: Ribbon UI — Brücken, Q-Zonen, Kollision (CAM), Nesting/Sim/Kosten/Maschine (Export)',
        'V5.5.0: AutoCAD Aliases — E=Erase, CO=Copy, RO=Rotate, MI=Mirror, SC=Scale, REC=Rectangle, PL=Polyline',
        'V5.5.0: Continuous Mode — Modification Tools starten nach Abschluss automatisch neu',
        'V5.5.0: Previous Selection (P) — Vorherige Auswahl in Modification-Tool Selektionsphase',
        'V5.5.0: Dynamic Input HUD — Koordinaten/Distanz/Winkel am Cursor (DynamicInput V1.0)',
        'V5.5.1: Visuelle Lead-Differenzierung — Cyan/Rot/Grün/Gelb/Magenta nach Zustand (canvas-renderer V3.13)',
        'V5.5.1: Lead-Routing isRotated/isAlternative Flags (cam-contour V4.8)',
        'V5.5.1: Dog-Leg Leads als isAlternative markiert für gelbe Darstellung',
        'V5.5.1: Offset-Tool Ghost-Preview — halbtransparente Vorschau beim Mausbewegen (advanced-tools V1.3)',
        'V5.5.1: Chamfer Continuous Mode — Tool bleibt nach Anwendung aktiv',
        'V5.5.1: Offset-Preview RubberBand-Type im Renderer (grün halbtransparent)',
        'V5.5.1: DXF Chaining Optimierung — Deque-Pattern, adaptive Grid-Zellgröße, Progress-Logging (dxf-parser V3.7)',
        'V5.5.1: BreakTool Finalisierung — Snap-Manager, CAM-Property-Vererbung, Vertex-Split-Fix, Continuous Mode (drawing-tools V2.4)',
        'V5.5.1: splitContourAtPoint Vertex-Degeneration Fix — keine Null-Längen-Segmente bei Vertex-Split (geometry-ops V2.2)',
        'V5.5.1: Overlap Break Tool (OB) — Kontur trennen + tangentiale Überlappung für Wasserstrahl-Einläufe (drawing-tools-ext V1.1)',
        'V5.5.1: splitAndOverlap() — Split + feste tangentiale Verlängerung mit C1-Stetigkeit (geometry-ops V2.3)',
        'V5.5.1: Ghost-Preview (Gelb #FFFF00) mit Pfeilspitze + Längenanzeige für Überlappungsrichtung',
        'V5.5.1: Slit-Modus (kerfWidth=0) automatisch bei Überlappungs-Konturen, Pipeline-Revalidierung',
        'V5.5.1: TEXT/MTEXT Glyph-Import — echte Buchstaben-Konturen via opentype.js (dxf-parser V3.8, text-tool V1.2)',
        'V5.5.1: TEXT Justierung — Group Codes 72/11/21 für Center/Right-Alignment korrekt ausgewertet',
        'V5.5.1: BBox-Fallback-Warnung wenn TEXT-Entities ohne geladenen Font importiert werden',
        'V5.6: ProjectManager V1.0 — Workspace-Verwaltung mit FSAPI Directory Picker',
        'V5.6: Workspace Sidebar — DXF-Dateiliste mit Klick-zum-Laden',
        'V5.6: Auto-Save (.bak.dxf) in regelmässigen Abständen (60s)',
        'V5.6: CNC-Unterordner automatisch im Workspace erstellt',
        'V5.6: IndexedDB Handle-Persistenz über Browser-Sitzungen',
        'V5.6: CNC-Export direkt in Workspace/CNC/ Ordner',
        'V5.7: Properties Panel Sidebar entfernt → CAM-Eigenschaften im Kontextmenu (Step 4)',
        'V5.7: Kontextmenu mit dynamischer CAM-Sektion (Quality, Piercing, Lead-In, Kerf)',
        'V5.7: Kontextmenu-Überlauf-Korrektur (Bildschirmrand-Check)',
        'V5.7: Null-safe DOM-Zugriffe nach Panel-Entfernung',
        'V5.8: Intarsien-Fix — Fugen-Offset wird jetzt angewendet (_applyIntarsiaOffset)',
        'V5.8: Intarsien-Fix — NEG-Export mit Clone statt Direkt-Referenz',
        'V5.8: Intarsien-Fix — Doppelte UI-Bindings (Shim-Block) entfernt',
        'V5.8: Intarsien-Preview — POS/NEG Toggle + Fugen-Offset-Linien im Canvas (orange/blau)',
        'V5.8: Intarsien-Preview — Gap-Änderung löst Canvas-Render aus',
        'V5.9: Bugfix-Audit — 35 Bugs behoben über 16 Dateien',
        'V5.9: KRITISCH — Nesting _ensureCCW Windungsrichtung korrigiert (NFP-Ergebnisse waren falsch)',
        'V5.9: KRITISCH — Sinumerik PP erstes Kontur-Segment nicht mehr übersprungen',
        'V5.9: KRITISCH — Clipboard-Paste im Canvas-Kontextmenu repariert (undoManager→clipboardManager)',
        'V5.9: KRITISCH — Toolpath-Simulator Canvas-ID korrigiert (main-canvas→canvas)',
        'V5.9: KRITISCH — TOTLEN c.selected→c.isSelected korrigiert',
        'V5.9: CNC — Math.abs() für getArea() im PP (NaN bei CW-Holes verhindert)',
        'V5.9: CNC — _fc() Null/NaN-Guard, R995 Integer-Format',
        'V5.9: CamContour — || → ?? für numerische Defaults (kerfWidth:0 etc. funktioniert jetzt)',
        'V5.9: CamContour — Dynamic Lead mutiert leadInLength nicht mehr permanent',
        'V5.9: CamContour — Alt-Lead Radius=0 → direkt Linear statt degenerierter Arc',
        'V5.9: Quality-Zones — Division-by-Zero bei Zero-Length Zones verhindert',
        'V5.9: Cost-Calculator — Quality-Index Off-by-One korrigiert (1-basiert→0-basiert)',
        'V5.9: Arc-Fitting — Zero-Tangent bei Duplikat-Punkten, Arc-Länge CW/CCW-korrekt',
        'V5.9: Canvas-Renderer — Panning early-return (kein Hover/Snap während Pan)',
        'V5.9: Advanced-Tools — NgonTool Fall-Through, ChamferTool Wrap-Around',
        'V5.9: Drawing-Tools — isModTool fehlende Aliases (CO/RO/MI/SC/E)',
        'V5.9: Command-Line — XSS via innerHTML verhindert (HTML-Escaping)',
        'V5.9: Snap-Manager — Null-Check für ARC startAngle/endAngle',
        'V5.9: DXF-Writer — ANSI_1252 Codepage (R12-konform), Closed-Polyline Duplikat-Check',
        'V5.9: Single-Mode — onContourClick wird gesichert/wiederhergestellt statt überschrieben',
        'V5.10 UX: Grössere Klickziele (Buttons, Kontextmenü) für Trackpad-Bedienung',
        'V5.10 UX: Custom CSS-Tooltips [data-tip] mit Beschreibung + Tastenkürzel auf allen Tool-Buttons',
        'V5.10 UX: F1 Shortcut-Hilfe-Dialog (3-Spalten: Zeichnen, Bearbeiten, Allgemein + Maus)',
        'V5.10 UX: Wizard-Step-Indikator im Tab-Strip (Badge + Step-Name)',
        'V5.10 UX: Verständlicherer Command-Line Prompt + Start-Hint mit F1-Verweis',
        'V6.0: Lead-Profiles V1.0 — 7 Built-in Profile (Material/Dicke), Benutzerdefinierte Profile (localStorage)',
        'V6.0: Smart Batch Rules — Automatische Lead-Zuweisung (disc→ext, hole→int, smallHole→center, slit→on_geometry)',
        'V6.0: Profil-Dropdown im CAM-Ribbon mit Abweichungs-Erkennung und Status-Anzeige',
        'V6.0: leadManualOverride Flag — schützt manuell geänderte Konturen vor Batch-Re-Apply (cam-contour V5.0)',
        'V6.0: Sinumerik PP V1.5 — Slit-Rückzug in Schnittrichtung (statt hardcoded X1.0), expliziter F-Code auf Kontur',
        'V6.0: PP _fc() NaN/Infinity-Warnung statt stiller 0.000 — maskiert keine Rechenfehler mehr',
        'V6.0: assertFinite() Guard im Geometrie-Kernel — NaN-Propagation frühzeitig abfangen',
        'V6.0: Math.tan() Guard in computeFillet(), Area NaN-Check in Kerf-Offset, segLen-Guard in Overcut',
        'V6.0: _pointInPolygon Epsilon-Check (1e-12 statt !== 0) — verhindert near-zero Division',
        'V6.0: Wizard-Validierung — warnt bei fehlenden Konturen/Nullpunkt/Schneidmodus vor Schrittwechsel',
        'V6.0: DXF-Fehlermeldungen kategorisiert — Splines, Encoding, Komplexität mit Lösungshinweisen',
        'V6.0: Export-Validierung — prüft ob G-Code tatsächlich erzeugt wurde (nicht leer)',
        'V6.0: Toolpath-Preview — 2D-Visualisierung im Vorschau-Modal (Eilgang, Konturen, Reihenfolge, Legende)',
        'V6.0: Disc-Fuellung — halbtransparente Flaeche fuer Teile in CAM-Modi, Holes werden ausgespart (even-odd)'
    ],
    
    print() {
        console.log('%c╔══════════════════════════════════════════════════════════╗', 'color: #00aa00; font-weight: bold');
        console.log('%c║  CeraCUT/CeraCUT V' + this.version + ' - Build ' + this.build + '            ║', 'color: #00aa00; font-weight: bold');
        console.log('%c║  Last Modified: ' + this.date + ' ' + this.time + '                   ║', 'color: #00aa00');
        console.log('%c╚══════════════════════════════════════════════════════════╝', 'color: #00aa00; font-weight: bold');
        
        console.log('%c[BUILD] Modules:', 'color: #888');
        for (const [name, info] of Object.entries(this.modules)) {
            console.log(`  ${name}: V${info.version} (${info.build})`);
        }
        
        console.log('%c[BUILD] Recent Changes:', 'color: #888');
        this.changes.forEach(c => console.log('  • ' + c));
    }
};

// Auto-Print beim Laden
if (typeof window !== 'undefined') {
    window.addEventListener('DOMContentLoaded', () => {
        CERACUT_BUILD.print();
    });
}

// Export für Node.js Tests
if (typeof module !== 'undefined' && module.exports) {
    module.exports = CERACUT_BUILD;
}
